src/Entity/SecurityUser.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

const ADMIN = 'ADMIN';
const REDACTEUR = 'REDACTEUR';
const USER = 'USER';

/**
 * @ORM\Entity(repositoryClass="App\Repository\SecurityUserRepository")
 *  * @UniqueEntity(
 *     fields={"email"},
 *     message="Ce mail est deja utilisé."
 * )
 */
class SecurityUser implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=8,minMessage="Votre mot de passe doit faire au moins 8 caractères")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas taper le même mot de passe")
     */
    private $confirm_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email
     */
    private $email;

    /**
     * @var Message
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="securityUser")
     */
    private $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }

    /**
     * @param mixed $confirm_password
     */
    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return array('ROLE_USER');
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->username;
        // TODO: Implement getUsername() method.
    }

    /**
     * @param mixed $username
     */
    public function setUsername($username): void
    {
        $this->username = $username;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setSecurityUser($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getSecurityUser() === $this) {
                $message->setSecurityUser(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\SecurityUser;
use App\Form\SecurityUserPasswordType;
use App\Form\SecurityUserProfilType;
use App\Form\SecurityUserRoleType;
use App\Form\SecurityUserType;
use App\Services\SecurityService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class SecurityController extends AbstractController
{
    /**
     * @var SecurityServiceService
     */
    private $SecurityService;

    public function __construct(SecurityService $SecurityService)
    {
        $this->SecurityService = $SecurityService;
    }

    /**
     * @Route("/registration", name="registration")
     */
    public function registration(Request $request)
    {
        $SecurityUser = new SecurityUser();
        $form = $this->createForm(SecurityUserType::class, $SecurityUser);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $SecurityUser->setRole("ROLE_USER");
            $this->SecurityService->post($SecurityUser);
            return $this->redirect("/login");
        }
        return $this->render('security/registration.html.twig', [
            'controller_name' => 'SecurityController',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/changUser/{idUser}", name="changUser")
     */
    public function changUser(Request $request,$idUser)
    {
        $SecurityUser = $this->SecurityService->get($idUser);

        $form = $this->createForm(SecurityUserProfilType::class, $SecurityUser);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->SecurityService->post($SecurityUser);
            return $this->redirect("/showProfil/$idUser");
        }
        return $this->render('security/registration.html.twig', [
            'controller_name' => 'SecurityController',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/changRole/{idUser}", name="changRole")
     */
    public function changRole(Request $request,$idUser)
    {

        $SecurityUser = $this->SecurityService->get($idUser);

        $form = $this->createForm(SecurityUserRoleType::class, $SecurityUser);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->SecurityService->post($SecurityUser);
            return $this->redirect("/showProfil/$idUser");
        }
        return $this->render('security/registration.html.twig', [
            'controller_name' => 'SecurityController',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/changPassword/{idUser}", name="changPassword")
     */
    public function changPassword(Request $request,$idUser)
    {

        $SecurityUser = $this->SecurityService->get($idUser);

        $form = $this->createForm(SecurityUserPasswordType::class, $SecurityUser);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->SecurityService->post($SecurityUser);
            return $this->redirect("/showProfil/$idUser");
        }
        return $this->render('security/registration.html.twig', [
            'controller_name' => 'SecurityController',
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/login", name="security_login")
     */
    public function login(AuthenticationUtils $authenticationUtils)
    {
        $error = $authenticationUtils->getLastAuthenticationError();

        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', array(
            'last_username' => $lastUsername,
            'error' => $error,
        ));
    }

    /**
     * @Route("/logout", name="security_logout")
     */
    public function logout()
    {
        return $this->render('security/login.html.twig', [
            'controller_name' => 'SecurityController',
        ]);
    }

    /**
     * @Route("/showProfil/{idUser}", name="showProfil")
     */
    public function showProfil($idUser = null)
    {
            $user = $this->SecurityService->get($idUser);

        return $this->render('security/showProfil.html.twig', [
            'controller_name' => 'SecurityController',
            'user' => $user
        ]);
    }

    /**
     * @Route("/panelAdmin", name="panelAdmin")
     */
    public function panelAdmin()
    {
        $listUser = $this->SecurityService->getAll();
        return $this->render('security/panelAdmin.html.twig', [
            'controller_name' => 'SecurityController',
            'listUser' => $listUser,
        ]);
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Login</h1>

    {% if error != null %}
        <p style="color:red;"> Adresse Mail ou mot de passe invalide</p>
    {% endif %}

    <form action="{{ path('security_login') }}" method="post">
        <div class="form-group">
            {% if error != null %}
                <input value="{{ last_username }}" required name="_username" type="text" class="form-control">
            {% else %}
            <input placeholder="Adresse email ..." required name="_username" type="text" class="form-control">
            {% endif %}
        </div>

        <div class="form-group">
            <input placeholder="Password ..." required name="_password" type="password" class="form-control">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Connexion</button>
        </div>
    </form>


{% endblock %}

templates/security/panelAdmin.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Panel Admin</h1>


        <div class="responsive-table-line" style="margin:0px auto;max-width:700px;">
            <table class="table table-bordered table-condensed table-body-center">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Mail</th>
                    <th>Role</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
    {% for user in listUser %}
                <tr>
                    <th>{{ user.username }}</th>
                    <th>{{ user.email }}</th>
                    <th>{{ user.role }}</th>
                    <th><a href="/showProfil/{{ user.getId() }}" class="btn btn-primary">Voir</a></th>
                </tr>
    {% endfor %}

                </tbody>
            </table>
        </div>
        {#{{ user.username }}#}
        {#{{ user.role }}#}

        {#<a href="/showProfil/{{ user.getId() }}" class="btn btn-primary">Voir</a>#}

        {#<br>#}


{% endblock %}

templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">Valider</button>
    {#{{ form_row(form.email)}}#}
    {#{{ form_row(form.username)}}#}
    {#{{ form_row(form.password)}}#}
    {#{{ form_row(form.confirmPassword)}}#}
    {{ form_end(form) }}

{% endblock %}

templates/security/showProfil.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1> Votre Profil</h1>

    <ul>
        <li> Pseudo : {{ user.username }}</li>
        <li> Mail : {{ user.email }}</li>
        {% if user.role == "ROLE_USER" %}
            <li> Role : utilisateur</li>
        {% endif %}
        {% if user.role == "ROLE_REDACTEUR" %}
            <li> Role : redacteur</li>
        {% endif %}
        {% if user.role == "ROLE_ADMIN" %}
            <li> Role : administrateur</li>
        {% endif %}

        {% if app.user.role == "ROLE_ADMIN" %}
            <a href="/changRole/{{ user.id }}" class="btn btn-info">modifier Role</a>
        {% endif %}

        <a href="/changUser/{{ user.id }}" class="btn btn-info">modifier Profil</a>
        <a href="/changPassword/{{ user.id }}" class="btn btn-info">modifier votre mot de passe</a>
        <a href="/" class="btn btn-primary">retour</a>
    </ul>

{% endblock %}